### ISSUE TITLE
[feature] 新增 SJTUReport/SJTUArticle 文档类

### ISSUE THREAD

**Issue by AlexaraWu** [sjtug/SJTUTeX#20]
计划新增 `sjtureport` 和 `sjtuarticle` 文档类，以满足学位论文之外的不同需求。

**Related Issues**:
sjtug/SJTUThesis#493

**Comment by LogCreative** [comment]
赞同，report 和 book 比较近，封面也可以一定程度上沿用 thesis 的封面，内部的章节设计上感觉可以灵活一些，可以用作大型项目的报告，或者是贴近于一些校内项目的模板，比如：

实习报告模板：[20220630143620_5160.docx](https://github.com/sjtug/SJTUTeX/files/10245175/20220630143620_5160.docx)

**Comment by LogCreative** [comment]
article 跟这两个类距离就比较远了，没有标题页，感觉可以用作课程小论文的模板，由于现在论文有限制页数的趋势（？），所以章节设计上可以从简。也可以适当的对章节添加颜色，比如：

https://github.com/LogCreative/quickdraw-classifier/blob/main/report/ML_CS420_Project_report.pdf
