### ISSUE TITLE
请问如何生成外文目录？

### ISSUE THREAD

**Issue by zhendonghou** [sjtug/SJTUTeX#56]

**Comment by LogCreative** [comment]
一般只会生成单一语种的目录，如果是英文论文，应当设置文档类选项 `lang=en`。

**Comment by AlexaraWu** [comment]
暂无计划支持多语种目录。

目录生成的原理倒是很简单。目录的条目会记录在一个外置文件中，一般是与主文档同名，扩展名为 `toc` 的文件。可以另外新建一个目录记录文件，例如 `toce`；使用 `\addcontentsline` 记录条目，再用 `\@starttoc` 生成目录表。
```latex
\makeatletter
\chapter{Contents}
\@starttoc{toce}
\makeatother

\chapter{绪论}
\addcontentsline{toce}{chapter}{Introduction}
```
