### ISSUE TITLE
希望可以支持 tabularray 宏包

### ISSUE THREAD

**Issue by peng1999** [sjtug/SJTUTeX#67]
[tabularray](https://www.ctan.org/pkg/tabularray) 是一个比较新的 All-in-one 表格宏包，其功能覆盖了 LaTeX2e 内置的表格环境，threeparttable 和 longtable 宏包。

目前为了使 tabularray 的风格和其他浮动体统一，我手动添加了如下两行配置：

```tex
\DefTblrTemplate{caption-sep}{default}{\quad}
\SetTblrStyle{caption}{font=\bfseries}
```

SJTUTeX 给 threeparttable 和 longtable 都提供了支持，可以在 `\sjtusetup` 中统一设置其格式。希望也可以支持 tabularray 的长表格环境以方便使用。

**Comment by AlexaraWu** [comment]
暂无计划。`tabularray` 自己写了一套方法来处理 caption，和 `caption` 宏集不兼容。

FYI: https://github.com/lvjr/tabularray/discussions/352
